apiVersion: v1
kind: Service
metadata:
  name: hl-be-service
  namespace: default
  labels:
    app: hl-be
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hl-be
    
